// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// Export file: exported/behaviac_generated/behaviors/generated_behaviors.cs
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;

namespace behaviac
{
	// Source file: FirstBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_FirstBT_node0 : behaviac.Action
	{
		public Action_bt_FirstBT_node0()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).SayHello();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_FirstBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("FirstBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				Action_bt_FirstBT_node0 node0 = new Action_bt_FirstBT_node0();
				node0.SetClassNameString("Action");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node0);
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: LoopBT

	[behaviac.GeneratedTypeMetaInfo()]
	class DecoratorLoop_bt_LoopBT_node0 : behaviac.DecoratorLoop
	{
		public DecoratorLoop_bt_LoopBT_node0()
		{
			m_bDecorateWhenChildEnds = true;
			m_bDoneWithinFrame = false;
		}
		protected override int GetCount(Agent pAgent)
		{
			return 3;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_LoopBT_node1 : behaviac.Action
	{
		public Action_bt_LoopBT_node1()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).SayHello();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_LoopBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("LoopBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				DecoratorLoop_bt_LoopBT_node0 node0 = new DecoratorLoop_bt_LoopBT_node0();
				node0.SetClassNameString("DecoratorLoop");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node0);
				{
					Action_bt_LoopBT_node1 node1 = new Action_bt_LoopBT_node1();
					node1.SetClassNameString("Action");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: SelectBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Assignment_bt_SelectBT_node1 : behaviac.Assignment
	{
		public Assignment_bt_SelectBT_node1()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			int opr = 6;
			pAgent.SetVariable<int>("p1", 2082220067u, opr);
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_SelectBT_node3 : behaviac.Condition
	{
		public Condition_bt_SelectBT_node3()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			int opl = (int)AgentMetaVisitor.GetProperty(pAgent, "p1");
			int opr = 8;
			bool op = opl > opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_SelectBT_node4 : behaviac.Action
	{
		public Action_bt_SelectBT_node4()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).SayHello();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_SelectBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("SelectBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				Sequence node0 = new Sequence();
				node0.SetClassNameString("Sequence");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node0);
				{
					Assignment_bt_SelectBT_node1 node1 = new Assignment_bt_SelectBT_node1();
					node1.SetClassNameString("Assignment");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				{
					Selector node2 = new Selector();
					node2.SetClassNameString("Selector");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node2);
					{
						Condition_bt_SelectBT_node3 node3 = new Condition_bt_SelectBT_node3();
						node3.SetClassNameString("Condition");
						node3.SetId(3);
#if !BEHAVIAC_RELEASE
						node3.SetAgentType("FirstAgent");
#endif
						node2.AddChild(node3);
						node2.SetHasEvents(node2.HasEvents() | node3.HasEvents());
					}
					{
						Action_bt_SelectBT_node4 node4 = new Action_bt_SelectBT_node4();
						node4.SetClassNameString("Action");
						node4.SetId(4);
#if !BEHAVIAC_RELEASE
						node4.SetAgentType("FirstAgent");
#endif
						node2.AddChild(node4);
						node2.SetHasEvents(node2.HasEvents() | node4.HasEvents());
					}
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: SequenceBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Assignment_bt_SequenceBT_node1 : behaviac.Assignment
	{
		public Assignment_bt_SequenceBT_node1()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			int opr = 6;
			pAgent.SetVariable<int>("p1", 2082220067u, opr);
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_SequenceBT_node2 : behaviac.Condition
	{
		public Condition_bt_SequenceBT_node2()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			int opl = (int)AgentMetaVisitor.GetProperty(pAgent, "p1");
			int opr = 4;
			bool op = opl > opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_SequenceBT_node3 : behaviac.Action
	{
		public Action_bt_SequenceBT_node3()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).SayHello();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_SequenceBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("SequenceBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				Sequence node0 = new Sequence();
				node0.SetClassNameString("Sequence");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node0);
				{
					Assignment_bt_SequenceBT_node1 node1 = new Assignment_bt_SequenceBT_node1();
					node1.SetClassNameString("Assignment");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				{
					Condition_bt_SequenceBT_node2 node2 = new Condition_bt_SequenceBT_node2();
					node2.SetClassNameString("Condition");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node2);
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				{
					Action_bt_SequenceBT_node3 node3 = new Action_bt_SequenceBT_node3();
					node3.SetClassNameString("Action");
					node3.SetId(3);
#if !BEHAVIAC_RELEASE
					node3.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node3);
					node0.SetHasEvents(node0.HasEvents() | node3.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

	// Source file: InstanceBT

	[behaviac.GeneratedTypeMetaInfo()]
	class Assignment_bt_InstanceBT_node1 : behaviac.Assignment
	{
		public Assignment_bt_InstanceBT_node1()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			int opr = 8;
			behaviac.Agent pAgent_opl = behaviac.Utils.GetParentAgent(pAgent, "SecondAgentInstance");
			pAgent_opl.SetVariable<int>("p2", 1462860768u, opr);
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Assignment_bt_InstanceBT_node2 : behaviac.Assignment
	{
		public Assignment_bt_InstanceBT_node2()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			EBTStatus result = EBTStatus.BT_SUCCESS;
			int opr = 5;
			behaviac.Agent pAgent_opl = (SecondAgent)AgentMetaVisitor.GetProperty(pAgent, "pInstance");
			pAgent_opl.SetVariable<int>("p2", 1462860768u, opr);
			return result;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Condition_bt_InstanceBT_node3 : behaviac.Condition
	{
		public Condition_bt_InstanceBT_node3()
		{
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			behaviac.Agent pAgent_opl = behaviac.Utils.GetParentAgent(pAgent, "SecondAgentInstance");
			int opl = (int)AgentMetaVisitor.GetProperty(pAgent_opl, "p2");
			behaviac.Agent pAgent_opr = (SecondAgent)AgentMetaVisitor.GetProperty(pAgent, "pInstance");
			int opr = (int)AgentMetaVisitor.GetProperty(pAgent_opr, "p2");
			bool op = opl > opr;
			return op ? EBTStatus.BT_SUCCESS : EBTStatus.BT_FAILURE;
		}
	}

	[behaviac.GeneratedTypeMetaInfo()]
	class Action_bt_InstanceBT_node4 : behaviac.Action
	{
		public Action_bt_InstanceBT_node4()
		{
			this.m_resultOption = EBTStatus.BT_SUCCESS;
		}
		protected override EBTStatus update_impl(behaviac.Agent pAgent, behaviac.EBTStatus childStatus)
		{
			((FirstAgent)pAgent).SayHello();
			return EBTStatus.BT_SUCCESS;
		}
	}

	public static class bt_InstanceBT
	{
		public static bool build_behavior_tree(BehaviorTree bt)
		{
			bt.SetClassNameString("BehaviorTree");
			bt.SetId(-1);
			bt.SetName("InstanceBT");
			bt.IsFSM = false;
#if !BEHAVIAC_RELEASE
			bt.SetAgentType("FirstAgent");
#endif
			// children
			{
				Sequence node0 = new Sequence();
				node0.SetClassNameString("Sequence");
				node0.SetId(0);
#if !BEHAVIAC_RELEASE
				node0.SetAgentType("FirstAgent");
#endif
				bt.AddChild(node0);
				{
					Assignment_bt_InstanceBT_node1 node1 = new Assignment_bt_InstanceBT_node1();
					node1.SetClassNameString("Assignment");
					node1.SetId(1);
#if !BEHAVIAC_RELEASE
					node1.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node1);
					node0.SetHasEvents(node0.HasEvents() | node1.HasEvents());
				}
				{
					Assignment_bt_InstanceBT_node2 node2 = new Assignment_bt_InstanceBT_node2();
					node2.SetClassNameString("Assignment");
					node2.SetId(2);
#if !BEHAVIAC_RELEASE
					node2.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node2);
					node0.SetHasEvents(node0.HasEvents() | node2.HasEvents());
				}
				{
					Condition_bt_InstanceBT_node3 node3 = new Condition_bt_InstanceBT_node3();
					node3.SetClassNameString("Condition");
					node3.SetId(3);
#if !BEHAVIAC_RELEASE
					node3.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node3);
					node0.SetHasEvents(node0.HasEvents() | node3.HasEvents());
				}
				{
					Action_bt_InstanceBT_node4 node4 = new Action_bt_InstanceBT_node4();
					node4.SetClassNameString("Action");
					node4.SetId(4);
#if !BEHAVIAC_RELEASE
					node4.SetAgentType("FirstAgent");
#endif
					node0.AddChild(node4);
					node0.SetHasEvents(node0.HasEvents() | node4.HasEvents());
				}
				bt.SetHasEvents(bt.HasEvents() | node0.HasEvents());
			}
			return true;
		}
	}

}
