// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

namespace behaviac
{
	public class CompareValue_FirstEnum : ICompareValue<FirstEnum>
	{
		public override bool Equal(FirstEnum lhs, FirstEnum rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(FirstEnum lhs, FirstEnum rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(FirstEnum lhs, FirstEnum rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(FirstEnum lhs, FirstEnum rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(FirstEnum lhs, FirstEnum rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(FirstEnum lhs, FirstEnum rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_FirstStruct : ICompareValue<FirstStruct>
	{
		public override bool Equal(FirstStruct lhs, FirstStruct rhs)
		{
			return (lhs.s1 == rhs.s1) && (lhs.s2 == rhs.s2);
		}
		public override bool NotEqual(FirstStruct lhs, FirstStruct rhs)
		{
			return !Equal(lhs, rhs);
		}
	}

	public class CompareValue_HeroStruct : ICompareValue<HeroStruct>
	{
		public override bool Equal(HeroStruct lhs, HeroStruct rhs)
		{
			return (lhs.age == rhs.age) && (lhs.uid == rhs.uid);
		}
		public override bool NotEqual(HeroStruct lhs, HeroStruct rhs)
		{
			return !Equal(lhs, rhs);
		}
	}


	public class BehaviorLoaderImplement : BehaviorLoader
	{
		class CInstanceConst_FirstStruct : CInstanceConst<FirstStruct>
		{
			IInstanceMember _s1;
			IInstanceMember _s2;

			public CInstanceConst_FirstStruct(string typeName, string valueStr) : base(typeName, valueStr)
			{
				List<string> paramStrs = behaviac.StringUtils.SplitTokensForStruct(valueStr);
				Debug.Check(paramStrs != null && paramStrs.Count == 2);

				_s1 = (CInstanceMember<int>)AgentMeta.ParseProperty<int>(paramStrs[0]);
				_s2 = (CInstanceMember<int>)AgentMeta.ParseProperty<int>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_s1 != null);
				Debug.Check(_s2 != null);

				_value.s1 = ((CInstanceMember<int>)_s1).GetValue(self);
				_value.s2 = ((CInstanceMember<int>)_s2).GetValue(self);
			}
		};

		class CInstanceConst_HeroStruct : CInstanceConst<HeroStruct>
		{
			IInstanceMember _age;
			IInstanceMember _uid;

			public CInstanceConst_HeroStruct(string typeName, string valueStr) : base(typeName, valueStr)
			{
				List<string> paramStrs = behaviac.StringUtils.SplitTokensForStruct(valueStr);
				Debug.Check(paramStrs != null && paramStrs.Count == 2);

				_age = (CInstanceMember<int>)AgentMeta.ParseProperty<int>(paramStrs[0]);
				_uid = (CInstanceMember<int>)AgentMeta.ParseProperty<int>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_age != null);
				Debug.Check(_uid != null);

				_value.age = ((CInstanceMember<int>)_age).GetValue(self);
				_value.uid = ((CInstanceMember<int>)_uid).GetValue(self);
			}
		};

		private class CMethod_behaviac_Agent_VectorAdd : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorAdd()
			{
			}

			public CMethod_behaviac_Agent_VectorAdd(CMethod_behaviac_Agent_VectorAdd rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorAdd(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorAdd((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorClear : CAgentMethodVoidBase
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorClear()
			{
			}

			public CMethod_behaviac_Agent_VectorClear(CMethod_behaviac_Agent_VectorClear rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorClear(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				behaviac.Agent.VectorClear((IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorContains : CAgentMethodBase<bool>
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorContains()
			{
			}

			public CMethod_behaviac_Agent_VectorContains(CMethod_behaviac_Agent_VectorContains rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorContains(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				_returnValue.value = behaviac.Agent.VectorContains((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorLength : CAgentMethodBase<int>
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorLength()
			{
			}

			public CMethod_behaviac_Agent_VectorLength(CMethod_behaviac_Agent_VectorLength rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorLength(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				_returnValue.value = behaviac.Agent.VectorLength((IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorRemove : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorRemove()
			{
			}

			public CMethod_behaviac_Agent_VectorRemove(CMethod_behaviac_Agent_VectorRemove rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorRemove(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorRemove((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}


		public override bool Load()
		{
			AgentMeta.TotalSignature = 3680386274;

			AgentMeta meta;

			// behaviac.Agent
			meta = new AgentMeta(24743406);
			AgentMeta._AgentMetas_[2436498804] = meta;
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { behaviac.Agent.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// FirstAgent
			meta = new AgentMeta(1008544719);
			AgentMeta._AgentMetas_[1778122110] = meta;
			meta.RegisterMemberProperty(2956534501, new CMemberProperty<FirstStruct>("firstStruct", delegate(Agent self, FirstStruct value) { ((FirstAgent)self).firstStruct = value; }, delegate(Agent self) { return ((FirstAgent)self).firstStruct; }));
			meta.RegisterMemberProperty(576049271, new CMemberProperty<HeroStruct>("heroStruct", delegate(Agent self, HeroStruct value) { ((FirstAgent)self).heroStruct = value; }, delegate(Agent self) { return ((FirstAgent)self).heroStruct; }));
			meta.RegisterMethod(3345343196, new CAgentMethodVoid<int>(delegate(Agent self, int val) { }) /* event_task */);
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { FirstAgent.LogMessage(param0); }));
			meta.RegisterMethod(702722749, new CAgentMethodVoid<string>(delegate(Agent self, string txt) { ((FirstAgent)self).Say(txt); }));
			meta.RegisterMethod(1505908390, new CAgentMethodVoid(delegate(Agent self) { ((FirstAgent)self).SayHello(); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			AgentMeta.Register<behaviac.Agent>("behaviac.Agent");
			AgentMeta.Register<FirstAgent>("FirstAgent");
			AgentMeta.Register<FirstEnum>("FirstEnum");
			ComparerRegister.RegisterType<FirstEnum, CompareValue_FirstEnum>();
			AgentMeta.Register<FirstStruct>("FirstStruct");
			ComparerRegister.RegisterType<FirstStruct, CompareValue_FirstStruct>();
			AgentMeta.Register<HeroStruct>("HeroStruct");
			ComparerRegister.RegisterType<HeroStruct, CompareValue_HeroStruct>();
			return true;
		}

		public override bool UnLoad()
		{
			AgentMeta.UnRegister<behaviac.Agent>("behaviac.Agent");
			AgentMeta.UnRegister<FirstAgent>("FirstAgent");
			AgentMeta.UnRegister<FirstEnum>("FirstEnum");
			AgentMeta.UnRegister<FirstStruct>("FirstStruct");
			AgentMeta.UnRegister<HeroStruct>("HeroStruct");
			return true;
		}
	}
}
