// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

public class FirstAgent : behaviac.Agent
///<<< BEGIN WRITING YOUR CODE FirstAgent
///<<< END WRITING YOUR CODE
{
	private FirstEnum firstEnum = FirstEnum.A;
	public void _set_firstEnum(FirstEnum value)
	{
		firstEnum = value;
	}
	public FirstEnum _get_firstEnum()
	{
		return firstEnum;
	}

	public FirstStruct firstStruct = new FirstStruct();

	public HeroStruct heroStruct = new HeroStruct();

	public HeroType heroType = HeroType.ZhanShi;

	public void Say(string txt)
	{
///<<< BEGIN WRITING YOUR CODE Say

        Loger.LogFormat("FirstAgent Say: {0},  firstStruct={1},  heroStruct={2}, firstEnum={3}, heroType={4}", txt, firstStruct, heroStruct, firstEnum, heroType);

///<<< END WRITING YOUR CODE
	}

	public void SayHello()
	{
///<<< BEGIN WRITING YOUR CODE SayHello
        Loger.LogFormat("FirstAgent SayHello firstStruct={0}, heroStruct={1}, firstEnum={2}, heroType={3}", firstStruct, heroStruct, firstEnum, heroType);
///<<< END WRITING YOUR CODE
	}

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

